pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                def mvnHome = tool name: 'Jenkins-maven', type: 'maven'
				def mvnCMD = "${mvnHome}/bin/mvn"
				sh "${mvnCMD} clean package"
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
